[build]
builder = "DOCKERFILE"
dockerfilePath = "ehrbase-db/Dockerfile"
watchPatterns = ["ehrbase-db/**"]

[deploy]
healthcheckPath = ""
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
